
email = "Bogdan Filipchuk <bogdan.filipchuk@sagetechcorp.com>"
emailx = "bogdan.filipchuk@sagetechcorp.com"
imap_server = "outlook.office365.com:993"
smtp_server = "smtp.office365.com:587"
username = "bogdan.filipchuk@sagetechcorp.com"

# Bcc Yourself when sending
echo = true

